# Generated by Django 5.2.4 on 2025-07-10 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='class_name',
            new_name='grade',
        ),
    ]
