# Generated by Django 5.2 on 2025-09-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='deposit_slip',
            field=models.FileField(upload_to='slips/'),
        ),
    ]
