# Generated by Django 5.2.6 on 2025-09-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_deposit_slip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='deposit_slip',
            field=models.FileField(upload_to=''),
        ),
    ]
